### ISSUE TITLE
Bug in Travis when push in 47deg.github.io

### ISSUE THREAD

**Issue by anamariamv** [47deg/org#69] opened 2018-01-11 11:55 UTC
```git push using:  https://47deg:[secure]@github.com/47deg/47deg.github.io.git master
To https://github.com/47deg/47deg.github.io.git
 ! [rejected]        d5fab7bc8b27b5867ab34200bf993b506211db36 -> master (non-fast-forward)
error: failed to push some refs to 'https://47deg:[secure]@github.com/47deg/47deg.github.io.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
```

**Comment by purrgrammer** [comment] 2018-12-13 16:21
Duplicate of #72

**Closed as completed by purrgrammer** 2018-12-13 16:21 UTC
